#!/bin/bash

# Converts all PPM files in current directory to JPG
# Does not overwrite original PPM, makes a new copy
# Naming convention is "1.ppm", "2.ppm", etc.
# Uses the Netpbm library

files=`ls`
i=1
for f in $files
do
  if [ "${f: -4}" = ".ppm" ]
  then
    pnmtojpeg $f > "$i.jpg"
    ((i++))
    echo $f
  fi
done
